baseURL = "https://banhamslaw.com/"
languageCode = "en-us"
title = "Banham's Law"

disqusShortname = ""
googleAnalytics = ""
summaryLength = 40
pluralizeListTitles = false
enableemoji = false

theme = "ramium"

[params]
    description = "Your ability to procure caffeine is inversely proportional to your need for it"
    googleSearch = ""
    showDate = true # make false if dont want to show date
    math = false # best to enable this in the front matter of a page
    githubProfile = "davidbanham/banhamslaw/"

    tagsInHome = 40
    sectionsInHome = 5
    paginatePostsPerPage = 5
    paginateTagsPerPage = 6

[taxonomies]
    tag = "tags"

[markup.goldmark.renderer]
    unsafe = true

[menu]
    [[menu.main]]
        name = "Home"
        url = "/"
        weight = 1

    [[menu.main]]
        identifier = "blog"
        name = "Field Observations"
        weight = 2
            [[menu.main]]
                parent = "blog"
                name = "All Tags"
                url = "/tags/"
                weight = 1
            [[menu.main]]
                parent = "blog"
                name = "All Posts"
                url = "/posts/"
                weight = 3
